name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:

    staging:        # carpeta models/staging
      +database: "HACKATON_SILVER"
      +schema: "STAGING"          # opcional (puedes poner raw, silver, bronze…)
      +materialized: view

    marts:          # carpeta models/marts
      +database: "HACKATON_GOLD"
      +schema: "MARTS"            # opcional
      +materialized: view

    # Ejemplo heredado de tu plantilla original, lo dejo intacto
    example:
      +materialized: table